
export default function Home() {
  return (
    <div className="bg-black">HomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHHomeHomeHomeHomeHomeHomeHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
omeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
omeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
omeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
omeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom e</div>
  )
}
