
export default function Homes() {
  return (
    <div className="bg-black  m-36">HomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHHomeHomeHomeHomeHomeHomeHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
omeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
omeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
HomeHomeHomeHomeHomeHHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
omeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHomHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom
omeHomeHomHomeHomeHomeHomeHomeHomeHomHomeHomeHomeHomeHomeHomeHom e</div>
  )
}
